language: go
go:
    - tip
jdk:
    - oraclejdk8
    
sudo: true
notifications:
    email: false

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y default-jdk

install:
  - go get github.com/Sirupsen/logrus
  - go get "code.google.com/p/gcfg"
  - go get "github.com/gin-gonic/contrib/expvar"
  - go get "github.com/gin-gonic/gin"
  - go get "github.com/sohlich/go-plag/parser"
  - go get "golang.org/x/net/context"
  - go get "gopkg.in/mgo.v2/bson"
  - go get "gopkg.in/mgo.v2"
  - go get "gopkg.in/validator.v2"
  - go get "github.com/satori/go.uuid"
  - go get "github.com/stretchr/testify/assert"
  - go get "github.com/rifflock/lfshook"